### সব টাস্ক দেখা
GET http://localhost:8080/tasks

### Task By ID
GET http://localhost:8080/tasks/21

### নতুন টাস্ক বানানো
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "asdaf",
  "done": false
}

### টাস্ক বদলানো
PUT http://localhost:8080/tasks/21
Content-Type: application/json

{
  "title": "Learn Go deeply",
  "done": true
}

### টাস্ক মোছা
DELETE http://localhost:8080/tasks/21

### নেই এমন টাস্ক মোছা
DELETE http://localhost:8080/tasks/99

### পাতা ১ (প্রতি পাতায় ৫টা)
GET http://localhost:8080/tasks?page=1&per_page=5

### পাতা ২ (প্রতি পাতায় ৫টা)
GET http://localhost:8080/tasks?page=2&per_page=5

### শুধু শেষ হওয়া task
GET http://localhost:8080/tasks?done=true

### ভুল মান দিলে 400 আসবে
GET http://localhost:8080/tasks?page=abc