### সব টাস্ক দেখা
GET http://localhost:8080/tasks

### Task By ID
GET http://localhost:8080/tasks/21

### নতুন টাস্ক বানানো
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "asdaf",
  "done": false
}

### টাস্ক বদলানো
PUT http://localhost:8080/tasks/21
Content-Type: application/json

{
  "title": "Learn Go deeply",
  "done": true
}

### টাস্ক মোছা
DELETE http://localhost:8080/tasks/17

### নেই এমন টাস্ক মোছা
DELETE http://localhost:8080/tasks/99


### Trash দেখা
GET http://localhost:8080/tasks/trash

### ফেরত আনা
POST http://localhost:8080/tasks/1/restore